# Generated by Django 4.2.3 on 2023-07-13 06:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('building_type', models.BooleanField(blank=True, null=True)),
                ('street', models.CharField(max_length=20)),
                ('number', models.PositiveIntegerField()),
                ('enter', models.CharField(blank=True, max_length=5, null=True)),
                ('floor', models.PositiveIntegerField(blank=True, null=True)),
                ('appartement', models.PositiveIntegerField(blank=True, null=True)),
                ('password', models.CharField(blank=True, max_length=20, null=True)),
                ('spacial_comment', models.TextField(blank=True, db_column='spacial_comment', null=True)),
            ],
            options={
                'db_table': 'address',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('phone_number', models.IntegerField()),
                ('avg_tip', models.IntegerField(blank=True, null=True)),
                ('addresses', models.ManyToManyField(to='bro_delivery_app.address')),
            ],
            options={
                'db_table': 'customer',
            },
        ),
        migrations.CreateModel(
            name='Delivery_guy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('phone_number', models.IntegerField()),
                ('vehicle', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'delivery_guy',
            },
        ),
        migrations.CreateModel(
            name='Tip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tip', models.IntegerField()),
                ('spacial_comment', models.TextField(db_column='spacial_comment', null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='bro_delivery_app.customer')),
                ('delivery_guy', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='bro_delivery_app.delivery_guy')),
            ],
            options={
                'db_table': 'tip',
            },
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('phone_number', models.IntegerField()),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='bro_delivery_app.address')),
                ('customers', models.ManyToManyField(to='bro_delivery_app.customer')),
            ],
            options={
                'db_table': 'restaurant',
            },
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preparation_time', models.PositiveIntegerField(blank=True, null=True)),
                ('arrival_time', models.DateTimeField()),
                ('time_left', models.IntegerField()),
                ('time_late', models.IntegerField(blank=True, null=True)),
                ('payment', models.BooleanField()),
                ('price', models.FloatField()),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='bro_delivery_app.address')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='bro_delivery_app.customer')),
                ('delivery_guys', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='bro_delivery_app.delivery_guy')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='bro_delivery_app.restaurant')),
            ],
            options={
                'db_table': 'delivery',
            },
        ),
        migrations.AddField(
            model_name='customer',
            name='restaurants',
            field=models.ManyToManyField(to='bro_delivery_app.restaurant'),
        ),
        migrations.AddField(
            model_name='address',
            name='customers',
            field=models.ManyToManyField(to='bro_delivery_app.customer'),
        ),
    ]
