# Generated by Django 4.2.3 on 2023-08-09 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bro_delivery_app', '0003_delivery_guy_user_restaurant_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='status',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
