# Generated by Django 4.2.3 on 2023-08-09 23:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bro_delivery_app', '0009_remove_delivery_arrival_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delivery_guy',
            name='name',
        ),
        migrations.AlterField(
            model_name='customer',
            name='addresses',
            field=models.ManyToManyField(blank=True, null=True, to='bro_delivery_app.address'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='restaurants',
            field=models.ManyToManyField(blank=True, null=True, to='bro_delivery_app.restaurant'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='delivery_guy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='bro_delivery_app.delivery_guy'),
        ),
    ]
