# Generated by Django 4.2.3 on 2023-08-10 01:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bro_delivery_app', '0010_remove_delivery_guy_name_alter_customer_addresses_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delivery_guy',
            name='vehicle',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='name',
        ),
    ]
