# Generated by Django 4.2.3 on 2023-08-10 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bro_delivery_app', '0012_alter_restaurant_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='addresses',
            field=models.ManyToManyField(to='bro_delivery_app.address'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='restaurants',
            field=models.ManyToManyField(to='bro_delivery_app.restaurant'),
        ),
    ]
