# Generated by Django 4.2.3 on 2023-08-10 02:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bro_delivery_app', '0013_alter_customer_addresses_alter_customer_restaurants'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='bro_delivery_app.address'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='customers',
            field=models.ManyToManyField(null=True, to='bro_delivery_app.customer'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, related_name='restaurant', to=settings.AUTH_USER_MODEL),
        ),
    ]
