# Generated by Django 4.2.3 on 2023-08-10 03:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bro_delivery_app', '0014_alter_restaurant_address_alter_restaurant_customers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='addresses',
            field=models.ManyToManyField(blank=True, null=True, to='bro_delivery_app.address'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='restaurants',
            field=models.ManyToManyField(blank=True, null=True, to='bro_delivery_app.restaurant'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='bro_delivery_app.address'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='customers',
            field=models.ManyToManyField(blank=True, null=True, to='bro_delivery_app.customer'),
        ),
    ]
