# Generated by Django 4.2.3 on 2023-08-10 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bro_delivery_app', '0015_alter_customer_addresses_alter_customer_restaurants_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='addresses',
            field=models.ManyToManyField(to='bro_delivery_app.address'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='restaurants',
            field=models.ManyToManyField(to='bro_delivery_app.restaurant'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='customers',
            field=models.ManyToManyField(to='bro_delivery_app.customer'),
        ),
    ]
