# Generated by Django 4.2.3 on 2023-08-19 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bro_delivery_app', '0017_alter_restaurant_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='customers',
            field=models.ManyToManyField(blank=True, null=True, to='bro_delivery_app.customer'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='restaurants',
            field=models.ManyToManyField(blank=True, null=True, to='bro_delivery_app.restaurant'),
        ),
    ]
