# Generated by Django 4.2.3 on 2023-08-26 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bro_delivery_app', '0020_alter_address_customers_alter_customer_addresses_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='status',
            field=models.CharField(default='משלוח חדש', max_length=20, null=True),
        ),
    ]
