# Generated by Django 4.2.3 on 2023-09-25 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bro_delivery_app', '0024_alter_delivery_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='name',
            field=models.CharField(default='none'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='status',
            field=models.CharField(default='משלוח חדש', max_length=20, null=True),
        ),
    ]
