# Generated by Django 4.2.3 on 2023-09-26 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bro_delivery_app', '0027_remove_delivery_guy_name_remove_restaurant_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='bro_delivery_app.address'),
        ),
    ]
