# Generated by Django 4.2.3 on 2023-09-26 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bro_delivery_app', '0029_alter_delivery_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='address',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='bro_delivery_app.address'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='delivery',
            name='customer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='bro_delivery_app.customer'),
            preserve_default=False,
        ),
    ]
